//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public int Id_extencion { get; set; }
        public byte[] Data { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Extension Extension { get; set; }
    }
}
